### ISSUE TITLE
FOUT for ajax webfont.js

### ISSUE THREAD

**Issue by papplo** [dadipaq/monsieurpress#1]
How do you manage to clear the **FOUT** (Flash of unstyled text) -issue with the Typekit webfont loading script? 
In my tests with Google Fonts it fetches the font-files almost 2-3 seconds later than the ordinary <link> method supplied by GF.

Reading on the Typekit/webfontloader github I understand there are classes applied to the <body> nevertheless, it doesn´t clear the FOUT-Issue.

**Comment by davidmanson** [comment]
Hi Papplo !

Two way to remove the FOUT :
1) In the function.php, juste find the line `wf.async = 'true';` and change it to `wf.async = 'false';` I think it should work.
2) Use the ordinary method supplied by Google Font, so first, remove the lines below 

```
/************************************
 Async Font Load
*************************************/
```

And add the google font style in the `front_assets_load` function like so :

```
function front_assets_load() {
    if (is_admin()) return;

    /* Enqueue theme script & style */
    wp_enqueue_style( 'monsieurpress-stylesheet', get_stylesheet_uri()  );
    wp_enqueue_script( 'monsieurpress-js', get_template_directory_uri() . '/js/dist/scripts.js', array('jquery'), '20160207', true);

    /* Enqueue google font */
    wp_enqueue_style( 'google-font', 'https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,400i,700');

    /* Enqueue comment-reply script if needed */
    if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
        wp_enqueue_script( 'comment-reply' );
    }
}
```

Hope it's what you are looking for.
