### ISSUE TITLE
Footer Nav

### ISSUE THREAD

**Issue by domedome** [dadipaq/monsieurpress#2]
Footer links are missing. No need to specify code, but here it is

<?php wp_nav_menu( array( 
           'theme_location' => 'footer-links', 
           'container' => false, 
) ); ?>

(great work man!!)

**Comment by dmanson-winn** [comment]
Just updated, thanks for the feedback :) I appreciate.

**Comment by davidmanson** [comment]
I just updated, thanks for the feedback :) I really appreciate
